Adding profiling instructions
mattermost/mattermost-load-test pull request #16
Opened 2016-10-07 00:09 UTC by it33

2016-10-12 15:46 UTC, coreyhulen approved these changes

2016-10-12 15:55 UTC, crspeller requested changes

2016-10-12 15:55 UTC, crspeller commented on install.rst
> +   Wait three (3) minutes for clean shut down.
For the new loadtests this is unnecessary. It has a clean shutdown procedure.

2016-10-12 15:55 UTC, crspeller commented on install.rst
> +   Wait three (3) minutes for clean shut down.
Unnecessary as log as the file exists you don't need to wait.

2016-10-27 16:04 UTC, coreyhulen commented
No longer applies.

2016-10-27 16:04 UTC, closed without merging