Update context.
mattermost/mattermost-load-test pull request #176
Opened 2019-12-04 15:07 UTC by metanerd

Summary

Update circleci context and add new s3 buckets.

2019-12-04 17:02 UTC, DSchalla requested changes
Added some changes, we currently do the following:
- PR goes into the `pr-builds` S3 bucket
- Releases go into the `releases` S3 bucket

The requested changes should reflect that accordingly, but please double check.

2019-12-04 17:02 UTC, DSchalla commented on .circleci/config.yml
> +          loadtest-binary: https://pr-builds.mattermost.com/loadtest-pr/${CIRCLE_BRANCH}/mattermost-load-test.tar.gz
```suggestion
          loadtest-binary: https://pr-builds.mattermost.com/loadtest/${CIRCLE_BRANCH}/mattermost-load-test.tar.gz
```

2019-12-04 17:02 UTC, DSchalla commented on .circleci/config.yml
> +          s3-copy-to: s3://pr-builds.mattermost.com/loadtest-pr/${CIRCLE_BRANCH}/
```suggestion
          s3-copy-to: s3://pr-builds.mattermost.com/loadtest/${CIRCLE_BRANCH}/
```

2019-12-04 17:02 UTC, DSchalla commented on .circleci/config.yml
> +          s3-copy-to: s3://pr-builds.mattermost.com/mattermost-load-test/${CIRCLE_TAG}/
```suggestion
          s3-copy-to: s3://releases.mattermost.com/mattermost-load-test/${CIRCLE_TAG}/
```

2019-12-04 17:02 UTC, DSchalla commented on .circleci/config.yml
> +          context: mattermost-ci-pr-builds-s3
```suggestion
          context: mattermost-release-s3
```

2019-12-04 17:02 UTC, DSchalla commented on .circleci/config.yml
> +          loadtest-binary: https://pr-builds.mattermost.com/mattermost-load-test/${CIRCLE_TAG}/mattermost-load-test.tar.gz
```suggestion
          loadtest-binary: https://releases.mattermost.com/mattermost-load-test/${CIRCLE_TAG}/mattermost-load-test.tar.gz
```

2019-12-04 17:02 UTC, DSchalla commented on .circleci/config.yml
> +          loadtest-binary: https://pr-builds.mattermost.com/mattermost-load-test/mattermost-load-test.tar.gz
```suggestion
          loadtest-binary: https://releases.mattermost.com/mattermost-load-test/mattermost-load-test.tar.gz
```

2019-12-04 17:02 UTC, DSchalla commented on .circleci/config.yml
> +          s3-copy-to: s3://pr-builds.mattermost.com/mattermost-load-test/
```suggestion
          s3-copy-to: s3://releases.mattermost.com/mattermost-load-test/
```

2019-12-04 17:02 UTC, DSchalla commented on .circleci/config.yml
> +          context: mattermost-ci-pr-builds-s3
```suggestion
          context: mattermost-release-s3
```

2019-12-04 17:04 UTC, DSchalla commented on .circleci/config.yml
>            context: mattermost-ci-s3
```suggestion
          context: mattermost-ci-pr-builds-s3
```

I cannot see that context currently existing, @cpanato was that a legacy one?

2019-12-04 17:04 UTC, DSchalla commented on .circleci/config.yml
>            context: mattermost-ci-s3
(For reference, the `mattermost-ci-s3` doesn't exist, the `mattermost-ci-pr-builds-s3` does)

2019-12-05 09:02 UTC, cpanato approved these changes

2019-12-05 09:50 UTC, DSchalla approved these changes

2019-12-05 10:16 UTC, merged