Incorporate latest load test configuration and setup parameters to install guides
mattermost/mattermost-load-test pull request #18
Opened 2016-10-11 19:19 UTC by jasonblais

2016-10-12 15:48 UTC, coreyhulen approved these changes
Some old lead test stuff, but it's probably ok.  You can get the details for the new scripts from CS.

2016-10-12 15:48 UTC, coreyhulen commented on install.rst
> +Setting: ``THREADCOUNT="15000"``
These are not really used anymore.  The load test script has changed.

2016-10-12 15:48 UTC, coreyhulen commented on install.rst
> +Setting: ``RAMPSEC="1000"``
These are not really used anymore.  The load test script has changed.

2016-10-12 15:56 UTC, crspeller requested changes
Needs to be updated for new load tests. (See Corey's comments)

2016-10-12 18:28 UTC, jasonblais commented
@crspeller Which script(s) should I link to instead? I can just remove the settings and link to them.

2016-10-14 18:41 UTC, crspeller commented
Will fix after merge.

2016-10-14 18:41 UTC, merged